"""phase1_initial_models

Revision ID: a41027ef13ac
Revises:
Create Date: 2026-04-09 20:49:17.047157

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a41027ef13ac"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "workflow",
            sa.Enum("advisory", "code_audit", name="workflowkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(length=2048), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "critical", "high", "medium", "low", "informational", name="severity", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "ssvc_action",
            sa.Enum("immediate", "act", "attend", "track", name="ssvcaction", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "confirmed_high",
                "confirmed_low",
                "unconfirmed",
                "false_positive",
                "accepted_risk",
                name="findingstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("triage_confidence", sa.Float(), nullable=True),
        sa.Column("duplicate_of", sa.String(length=512), nullable=True),
        sa.Column("duplicate_tracker", sa.String(length=64), nullable=True),
        sa.Column("duplicate_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "known_status",
            sa.Enum(
                "duplicate",
                "known_resolved",
                "known_accepted_risk",
                "new_instance",
                name="knownstatus",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cvss_vector", sa.String(length=256), nullable=True),
        sa.Column("cwe_ids", sa.JSON(), nullable=True),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reproduction", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=True),
        sa.Column(
            "workflow_type",
            sa.Enum("advisory", "code_audit", name="workflowkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=128), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_action_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("agent", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=256), nullable=False),
        sa.Column("tool_inputs", sa.JSON(), nullable=True),
        sa.Column("tool_output", sa.Text(), nullable=True),
        sa.Column("workflow_run_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_action_logs")
    op.drop_table("workflow_runs")
    op.drop_table("findings")
    # ### end Alembic commands ###
